# -------------------------------------------- Volume creation -----------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-volume-claim
  namespace: appscore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
# -------------------------------------------- Prometheus deployment -----------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: appscore
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
  labels:
    app: prometheus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pod
  template:
    metadata:
      labels:
        app: prometheus-pod
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          #resources:
            # requests:
            #   cpu: 500m
            #   memory: 500M
            # limits:
            #   cpu: 1
            #   memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-volume-claim
---
# Prometheus service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: appscore
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-pod
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090 
---